Script started on Sun Mar  7 22:57:56 2021
]0;wonheel1@crystalcove:hw4[wonheel1@crystalcove hw4]$ make
gcc -ansi -std=c99 -Wall -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c PhotoLab_v3.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libfilter.a Advanced.o DIPs.o
ranlib libfilter.a
gcc -ansi -std=c99 -Wall PhotoLab.o FileIO.o Image.o Test.o -L. -lfilter -o PhotoLab_v3 -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG  -c Test.c -o Test_DEBUG.o
gcc -ansi -std=c99 -Wall -c -DDEBUG  -c PhotoLab_v3.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall PhotoLab_DEBUG.o FileIO.o Image.o Test_DEBUG.o -L. -lfilter -o PhotoLabTest -lm
]0;wonheel1@crystalcove:hw4[wonheel1@crystalcove hw4]$ ./PhotoLab_v3 

-------------------------
 1: Load a PPM image
 2: Save image in PPM and JPEG format
 3: Run aging
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
 9: Enlarge image
10: Create square (crop) image
11: Adjust brightness and contrast
22: Test all functions
99: Exit

-------------------------
Please make your choice: 22
Segmentation fault (core dumped)
]0;wonheel1@crystalcove:hw4[wonheel1@crystalcove hw4]$ ./PhotoLab_v3[K[K[K[K[K[K[K[K[K[K[K[K[Kvalgrind --leak-check=full ./PhotoLabET[K[KTest 
==4394== Memcheck, a memory error detector
==4394== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==4394== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==4394== Command: ./PhotoLabTest
==4394== 
LoadImage & SaveImage tested!

Aging tested!

Sharpen tested!

Edge tested!

Noise tested!

Posterization tested!

Negative tested!

Enlarge tested!

==4394== Invalid read of size 1
==4394==    at 0x401EA1: Square (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==    by 0x4016F4: AutoTest (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==    by 0x400A7C: main (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==  Address 0x7ff013950 is not stack'd, malloc'd or (recently) free'd
==4394== 
==4394== 
==4394== Process terminating with default action of signal 11 (SIGSEGV)
==4394==  Access not within mapped region at address 0x7FF013950
==4394==    at 0x401EA1: Square (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==    by 0x4016F4: AutoTest (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==    by 0x400A7C: main (in /users/ugrad/2019/fall/wonheel1/EECS22W21/hw4/PhotoLabTest)
==4394==  If you believe this happened as a result of a stack
==4394==  overflow in your program's main thread (unlikely but
==4394==  possible), you can try to increase the size of the
==4394==  main thread stack using the --main-stacksize= flag.
==4394==  The main thread stack size used in this run was 10485760.
==4394== 
==4394== HEAP SUMMARY:
==4394==     in use at exit: 720,032 bytes in 4 blocks
==4394==   total heap usage: 53 allocs, 49 frees, 6,489,944 bytes allocated
==4394== 
==4394== LEAK SUMMARY:
==4394==    definitely lost: 0 bytes in 0 blocks
==4394==    indirectly lost: 0 bytes in 0 blocks
==4394==      possibly lost: 0 bytes in 0 blocks
==4394==    still reachable: 720,032 bytes in 4 blocks
==4394==         suppressed: 0 bytes in 0 blocks
==4394== Reachable blocks (those to which a pointer was found) are not shown.
==4394== To see them, rerun with: --leak-check=full --show-reachable=yes
==4394== 
==4394== For counts of detected and suppressed errors, rerun with: -v
==4394== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 8 from 6)
Segmentation fault (core dumped)
]0;wonheel1@crystalcove:hw4[wonheel1@crystalcove hw4]$ make clean
rm -f *.o *.jpg PhotoLab_v3 PhotoLabTest edge.ppm sharpen.ppm posterize.ppm aging.ppm negative.ppm noise.ppm enlarge.ppm square.ppm brightnessandcontrast.ppm  libfilter.a libFileIO.a
rm -f PhotoLab_v3
rm -f PhotoLabTest
]0;wonheel1@crystalcove:hw4[wonheel1@crystalcove hw4]$ exit
exit

Script done on Sun Mar  7 22:58:50 2021
