Script started on Mon Mar 15 21:34:22 2021
]0;wonheel1@crystalcove:hw5[wonheel1@crystalcove hw5]$ make clean
rm -f *.o TicTacWowWeeWow libfilter.a libFileIO.a
]0;wonheel1@crystalcove:hw5[wonheel1@crystalcove hw5]$ make 
gcc -ansi -std=c99 -Wall -c -g Game.c -o Game.o
gcc -ansi -std=c99 -Wall -c -g AI.c -o AI.o
gcc -ansi -std=c99 -Wall -c -g Settings.c -o Settings.o
gcc -ansi -std=c99 -Wall -c -g Play.c -o Play.o
gcc -ansi -std=c99 -Wall -c -g PlayList.c -o PlayList.o
gcc -ansi -std=c99 -Wall -c -g TicTacWowWeeWow.c -o TicTacWowWeeWow.o
ar rc libfilter.a Game.o AI.o Settings.o Play.o PlayList.o
ranlib libfilter.a
gcc -ansi -std=c99 -Wall TicTacWowWeeWow.o Game.o AI.o Settings.o Play.o PlayList.o -L. -lfilter -o TicTacWowWeeWow -lm
]0;wonheel1@crystalcove:hw5[wonheel1@crystalcove hw5]$ make clean[29Gvalgrind --leak-check=full ./TicTacWowWeeWow[29Gexit[Kvalgrind --leak-check=full ./TicTacWowWeeWow
==40454== Memcheck, a memory error detector
==40454== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==40454== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==40454== Command: ./TicTacWowWeeWow
==40454== 
Welcome to Tic-Tac-Wow-Wee-Wow!
1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 3
Entering Settings...
Please enter the setting options below...
1. Changing the players' character
2. Changing players' character color
3. Exiting setting
1
player 1 choose your char between A to Z
M
player 2 choose your char between A to Z
L
Entering Settings...
Please enter the setting options below...
1. Changing the players' character
2. Changing players' character color
3. Exiting setting
2
player 1 choose from the following list for your color please...
'r' for red, 'g' for green, 'y' for yellow, 'b' for blue', 'd' for default
r
player 2 choose from the following list for your color please...
'r' for red, 'g' for green, 'y' for yellow, 'b' for blue', 'd' for default
g
Entering Settings...
Please enter the setting options below...
1. Changing the players' character
2. Changing players' character color
3. Exiting setting
3
Setting completed!
1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 2
Level 1 (Inky) - picks first available move
Level 2 (Blinky) - picks a random available move
Level 3 (Pinky) - blocks Human from getting 3-in-a-row when possible
Level 4 (Clyde) - full tree search
Select a level: 2
Human v. AI game started
C  | | 
 -------
B  | | 
 -------
A  | | 
  1 2 3
Player 1, please choose your move:B2
C  | | 
 -------
B  |[31mM[0m| 
 -------
A  | | 
  1 2 3
AI is choosing its move:
C  | | 
 -------
B  |[31mM[0m| 
 -------
A [32mL[0m| | 
  1 2 3
Take back move? y/n: y
C  | | 
 -------
B  | | 
 -------
A  | | 
  1 2 3
Player 1, please choose your move:B2
C  | | 
 -------
B  |[31mM[0m| 
 -------
A  | | 
  1 2 3
AI is choosing its move:
C  | | 
 -------
B  |[31mM[0m| 
 -------
A [32mL[0m| | 
  1 2 3
Take back move? y/n: n
Player 1, please choose your move:A2  A3
C  | | 
 -------
B  |[31mM[0m| 
 -------
A [32mL[0m| |[31mM[0m
  1 2 3
AI is choosing its move:
C [32mL[0m| | 
 -------
B  |[31mM[0m| 
 -------
A [32mL[0m| |[31mM[0m
  1 2 3
Take back move? y/n: n
Player 1, please choose your move:B1
C [32mL[0m| | 
 -------
B [31mM[0m|[31mM[0m| 
 -------
A [32mL[0m| |[31mM[0m
  1 2 3
AI is choosing its move:
C [32mL[0m| | 
 -------
B [31mM[0m|[31mM[0m|[32mL[0m
 -------
A [32mL[0m| |[31mM[0m
  1 2 3
Take back move? y/n: n
Player 1, please choose your move:A2
C [32mL[0m| | 
 -------
B [31mM[0m|[31mM[0m|[32mL[0m
 -------
A [32mL[0m|[31mM[0m|[31mM[0m
  1 2 3
AI is choosing its move:
C [32mL[0m|[32mL[0m| 
 -------
B [31mM[0m|[31mM[0m|[32mL[0m
 -------
A [32mL[0m|[31mM[0m|[31mM[0m
  1 2 3
Take back move? y/n: n
Player 1, please choose your move:C3
C [32mL[0m|[32mL[0m|[31mM[0m
 -------
B [31mM[0m|[31mM[0m|[32mL[0m
 -------
A [32mL[0m|[31mM[0m|[31mM[0m
  1 2 3
The game is a tie!
Save Replay? y/n: y
Replay Saved.
1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 4
Thanks for playing. Exiting game...
==40454== 
==40454== HEAP SUMMARY:
==40454==     in use at exit: 0 bytes in 0 blocks
==40454==   total heap usage: 25 allocs, 25 frees, 4,090 bytes allocated
==40454== 
==40454== All heap blocks were freed -- no leaks are possible
==40454== 
==40454== For counts of detected and suppressed errors, rerun with: -v
==40454== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;wonheel1@crystalcove:hw5[wonheel1@crystalcove hw5]$ ^Dexit

Script done on Mon Mar 15 21:35:50 2021
